[RTMP]
ListenAddr = ":1935"
[GateWay]
ListenAddr = ":8081"
[Jessica]
ListenAddr = ":8080"
[LogRotate]
Path = "logs"
[Cluster]
ListenAddr = ":2019"
[TS]
Path  = "resource"
[Record]
Path = "resource"
[RTSP]
AutoPublish = false
RtspURL = "rtsp://localhost/test"
[HLS]
EnableWrite = false
[HDL]
ListenAddr = ":2020"
[WebRTC]